apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeaffinty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: pod
      labels:
        app: myapp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - myapp
      containers:
      - image: nginx
        name: nginx-containers


#kubectl label node minikube app=myapp
    
     
 