apiVersion: apps/v1
metadata:
  name: replicaset
kind: ReplicaSet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp     
  template:
    metadata:
      name: nginx
      labels: 
        app: myapp
    spec: 
      containers:
      - name: nginx
        image: nginx
