apiVersion: v1
kind: Service
metadata: 
  name: fst-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 3001
  selector:    
    app: myapp
  template:
    metadata:
      name: fst-pod
      labels:
        app: myapp
    containers:
    - name: nginx
      image: nginx


#kubectl create -f filename

