apiVersion: apps/v1
kind: Deployment
metadata:
  name: taintexample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: Pod-taint
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "myapp"
        effect: "NoSchedule"


#kubectl create -f filename
#kubectl taint node nodename key=value:taintvaluenosheduler
  
        

       

